### ISSUE TITLE
Simplify the event loop by using a context manager

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#10]
The idea is to eventually move the analysis definition completely into the YAML file format.
An example of how this could look like (first ideas):

```yaml
version: 0.01

input:
  <snip>

modifiers:
  calibratedJets:
    code: cmsl1t.modifiers.calibratedJets
    reads: event.caloTowers
    creates: event.calibratedJets
    kwargs:
       calibration_file: /eos/..../myFile.lut

analysis:
  <snip>

output:
  <snip>
```

```python
with Session(config_file) as s:
    s.run()
```

The session manager implements three functions `__enter__`, `run` and `__exit__`.
`__enter__` would be used to
 - read the config
 - create all modifiers, etc
 - create the TreeChain and set the variables to be cached
 - create all histogram collections

`run` would be used to 
 - iterate over events
 - apply modifiers
 - fill histograms

`__exit__` would
 - write histograms to file
 - create summary
