### ISSUE TITLE
Producers need better configuration language

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#134]
Currently, producers face two problems:
 1. accessing event content can be awkward: `event[self.inputs['nSums']]`
 2. cannot run more than one copy of the same producer twice

To address the first one, we should change how producers are fed input.
Instead of `produce(self, event)` we could have `produce(self, inputs):` where `self.inputs['nSums']` would contain the unpacked value instead of the branch name.
Configuration example:
```yaml
...
  producers:
    - cmsl1t.producers.l1sums:
        inputs:
          nSums: L1Upgrade_nSums
          types: L1Upgrade_sumType
          ets: L1Upgrade_sumEt
          phis: L1Upgrade_sumPhi
        outputs:
          - l1Sums
```

For part two, we should change the way producers are defined, e.g.
```yaml
...
  producers:
    - cmsl1t.producers.l1sums:
        inputs:
          nSums: L1Upgrade_nSums
          types: L1Upgrade_sumType
          ets: L1Upgrade_sumEt
          phis: L1Upgrade_sumPhi
        outputs:
          - l1Sums
```
&rarr;
```yaml
...
  producers:
    - l1sums:
        module: cmsl1t.producers.l1sums
        inputs:
          nSums: L1Upgrade_nSums
          types: L1Upgrade_sumType
          ets: L1Upgrade_sumEt
          phis: L1Upgrade_sumPhi
        outputs:
          - l1Sums
```
this way we can add a second producer doing the same thing but on different inputs:
```yaml
      - emu_l1sums:
        module: cmsl1t.producers.l1sums
        inputs:
          nSums: emu_L1Upgrade_nSums
          types: emu_L1Upgrade_sumType
          ets: emu_L1Upgrade_sumEt
          phis: emu_L1Upgrade_sumPhi
        outputs:
          - emu_l1Sums
```
emu_L1Upgrade_sumPhi
