### ISSUE TITLE
Global filters

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#169]
Since making some progress on the vectorization front I realised that some things will be very different in that scenario. Filters are one such thing, so I started to create functions to deal with that.

Furthermore, it would be useful for event-level filters, e.g. `LumiFilter`, to define them the same way `producers` and `analyzers` are at the moment:

```yaml
analyzers:
     <name>:
       module: cmsl1t.analyzers.HW_Emu_jetMet_rates
      <params>
producers:
    <name>:
      module: cmsl1t.producers.l1sums_vectorized
      <params>
filters:
    <name>:
      module: cmsl1t.filters.luminosity.LuminosityFilter
      <params>
```

This can, of course, be later enriched to add a list of producers/analyzers this filter is valid for or pass their results directly to the analyzers (e.g via a producer of filter values).

For now, these should be correctly translated into event filters:
 - skip event if it does not pass all filters
 - mask events if they do not pass all filters (vectorized)
