### ISSUE TITLE
Config scope reduction for analysers

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#47]
Currently, analysers receive the full configuration in the constructor. This means that each analyser needs to understand the structure (sections, etc) of the configuration.
Instead, we should decouple this dependency by passing only relevant parts as `*args` or `**kwargs`.

This separation also adds functionality: with it in place you can have multiple instances of the same analyser with different parameters, further improving the reusability of code.
E.g. if a simple MET analyser exists, but you want to produce the same histograms for a different MET collection it would be as simple as changing one parameter in the config.

**Comment by kreczko** [comment]
Config for an analyzer should be reordered (by ConfigParser) to
```yaml
name: <analyzer name>
output_folder: "config.get('output', 'folder')"
plots_folder: "config.get('output', 'plots_folder')"
pu_bins: "config.try_get('analysis', 'pu_bins', [0, 999])"
thresholds: "config.try_get('analysis', 'thresholds', None)"
# update with local values if present
# insert analyzer specific bits here
```

Example:
```yaml
analysis:
  pu_bins: [25,50,999]
  analyzers:
    - cmsl1t.analyzers.inspector:
         inputs:
           - l1Sums_Htt
output:
  template:
     - output/jetMet_analyzer
     - "{date}_{run_number}_{sample_name}_{trigger_name}"
```

&rarr;
```yaml
name: cmsl1t.analyzers.inspector:
# global vars
pu_bins: [25,50,999]
output_folder: "output/jetMet_analyzer/20180725_2017_Data_SM-v1"
plots_folder: "output/jetMet_analyzer/20180725_2017_Data_SM-v1/plots-v1"
...
# local vars
inputs:
  - l1Sums_Htt
```

**Comment by kreczko** [comment]
@benkrikler @bundocka  Which notation do you find better?
```yaml
analyzers:
    demo1:
      module: cmsl1t.analyzers.demo_analyzer
      param1: 42
      param2: 42.5
    demo2:
      module: cmsl1t.analyzers.demo_analyzer
      ....
```
vs
```yaml
analyzers:
   - cmsl1t.analyzers.demo_analyzer:
       name: demo1
       module: cmsl1t.analyzers.demo_analyzer
       param1: 42
       param2: 42.5
  - cmsl1t.analyzers.demo_analyzer:
       name: demo2
      ....
```

The former has the benefit that it is impossible to have two analyzers with the same name while the latter is closer to what we currently have.
Personally I would go fo the former as it reduces the need to check for duplicates in the code.
