### ISSUE TITLE
Replacement of ntuple_config

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#5]
In the end we want to simply pass a configuration to a script and it should do the right thing.
For that we need two things:
 - a config format/schema
 - a config parser

For the config format we explored the YAML format which seems to be the most human-readable hierarchic solution.

Example:
```yaml
# maybe a version?
version: 0.01
name: Zero Bias Analysis
progress_bar:
  report_every: 1000
# or to switch it off
# progress_bar:
#   enable: False

input:
  files:
    - /afs/cern.ch/work/s/sbreeze/public/jets_and_sums/160717_r276653_ZeroBias_l1t-int-71p1/L1Ntuple_*.root
  sample
    name: Data  
    title: 2016 Data
  trigger:
    name: ZeroBias
    title: Zero Bias
  pileup_file: ""
  run_number: 276653

analysis:
  do_fit: False
  pu_type: 0PU
  pu_bins = 0,999

output:
  # template is a list here that is joined (os.path.join) in the config parser
  template: 
     - /afs/cern.ch/work/s/sbreeze/L1TriggerStudiesOutput
     - "/{date}_{sample_name}+run-{run_number}_{trigger_name}"
```
