### ISSUE TITLE
Generalisation of modifiers/analyzers

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#53]
Based on the discussion in the tutorial I was thinking of generalising modifiers and analyzers.
This allows to reuse logic but also to create generic versions for the most common use cases (e.g. efficiencies, resolution).

Further down the line, this can also be used to trace data to optimise access (i.e. create a data flow graph and only load the needed branches).

```yaml
analysis:
  analyzers:
    cmsl1t.analyzers.demo_analyzer:
       in: [nVertex, caloTowers, sums.caloMetBE]
  modifiers:
      - cmsl1t.recalc.met.l1MetNot28:
          in: caloTowers
          out: l1MetNot28
```

**Comment by kreczko** [comment]
This issue needs updating due to #80. With the new `EventReader` it is possible to add event content on the fly.

A possible solution to make a general version of
```yaml
producers:
      - cmsl1t.producers.met.l1MetNot28:
          in:
            - event.caloTowers
          out: 
            - event.l1MetNot28
```
Is to add producers similar to trees, e.g.
```python
eventReader.trees['cmsl1t.producers.met.l1MetNot28'= 'the above producer
...
event.l1MetNot28
# -> calls cmsl1t.producers.met.l1MetNot28 instance with 
met_producer.l1MetNot28
...
# inside the met_producer
@property
def l1MetNot28(self):
   if self.not_cached:
      calculate()
   return self._l1MetNot28
      
   
```

Producers will need their own caching mechanism for each event to cover the case of multiple outputs and things like `met_producer.l1MetNot28` would need to be [properties](https://docs.python.org/2/howto/descriptor.html#properties) of the producer.
Properties should be easier for the user to implement instead of customising `__getattr__(self, name)`.
