### ISSUE TITLE
Separate making plots from analyzer?

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#54]
Maybe it would be worth to separate plotting from analyzers (i.e. `Analyzer.make_plots`).

This can be done by specifying a new analysis entry called `plotter`:

```yaml
analysis:
  analyzers:
    - cmsl1t.analyzers.demo_analyzer
    ...
  modifiers:
    ...
  plotters:
    cmsl1t.plotting.efficiency:
      in: cmsl1t.analyzers.demo_analyzer
```
