### ISSUE TITLE
Configuration files for mapping L1TNtuple content

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#79]
# Overview
Due to lack of a better title, I will try to explain in detail in this issue.

For both developers and users who just want to specify variables to plot it is crucial to easily get an overview as to what is available.

This should be done in a human- and machine-readable form, so the current proposal will focus on a YAML config file.
The goal is to
 - automatically map ntuple content to YAML
 - allow to manually extend YAML to enable customisation (meta data, aliases).
 - allow for optional event content
 - adopt event reader to do the mapping

Aliases are meant to map, e.g.
 - `event.l1EventTree.Event.run` to `event.run`
 - `event.l1CaloTowerTree.L1CaloTowerTree.CaloTP.nHCALTP` to `event.caloTP_nHCALTP`

# Details

Example content YAML file:
```YAML
version: 1.0

content:
  l1EventTree/Event: # example with no aliases
    optional: false
    branches:
      run:
      event:
      lumi:

  l1CaloTowerTree/L1CaloTowerTree:
    optional: false
    branches:
      CaloTP.nHCALTP:
        aliases: 
          - caloTP_nHCALTP
  l1JetRecoTree/JetRecoTree:
    optional: true
    branches:
      Jet.nJets:
        aliases:
          - Jet_nJets
          - nJets
...
```
Due to duplication in the paths and names in the directories, trees and branch names it should be possible to automate most of the aliases.

This information can be used to produce a more intuitive mapping file:
```YAML
version: 1.0
mapping:
  event.l1CaloTowerTree.L1CaloTowerTree.CaloTP.nHCALTP: event.caloTP_nHCALTP
  event.l1EventTree.Event.run: event.run
  event.l1JetRecoTree.JetRecoTree.Jet.nJets: event.nJets
```
Ideally, the versioning information should be taken from the L1TNtuples directly, but they currently lack such information.

I expect that we will encounter some name-clashes for automated aliasing, but this has to be seen.
