### ISSUE TITLE
Introduce 'modifiers'

### ISSUE THREAD

**Issue by kreczko** [cms-l1t-offline/cms-l1t-analysis#9]
Modifiers have been proposed as a way to stop the EventReader to grow beyond any reasonable scope.
Modifiers, e.g. applying jet calibrations, should take parts of the basic event content, e.g. `event.caloTowers` to create a separate new collection `calibratedJets`.

We will need some glue (e.g. the Session class, see Notes.md) to then attach the new collection to the even.

Example without Session object:
```python
# creates calibratedJets
modifiers = [CalibrateJets(jetCalibrationFile)]
for event in events:
    for mod in modifiers:
        mod.apply_to(event)
    jets = event.calibratedJets
```

**Comment by kreczko** [comment]
In the config files each analyzer could register its own modifiers:
```yaml
modifiers:
  recalc.l1MetNot28:
    in: event.caloTowers
    out: event.l1MetNot28
  recalc.l1MetNot28HF:
    in: event.caloTowers
    out: event.l1MetNot28HF
```
which would be collected first and checked for duplicates.
Internally, instead of the above example, it would be better to attach the modifiers to the event.

The calculation should only happen once the new attribute, here `event.l1MetNot28`, is called. The result of the calculation should be cached!
